export const CALOS_JSON = [
	'Calo Duro em pé direito ',
	'Calo Duro em Halux direito ',
	'Calo Duro em Arteiro 1 direito ',
	'Calo Duro em Arteiro 2 direito ',
	'Calo Duro em Arteiro 3 direito ',
	'Calo Duro em Arteiro 4 direito ',
	'Calo Duro em pé esquerdo ',
	'Calo Duro em Halux esquerdo ',
	'Calo Duro em Arteiro 1 esquerdo ',
	'Calo Duro em Arteiro 2 esquerdo ',
	'Calo Duro em Arteiro 3 esquerdo ',
	'Calo Duro em Arteiro 4 esquerdo ',
	'Calo Interdigital em pé direito ',
	'Calo Interdigital em Halux direito ',
	'Calo Interdigital em Arteiro 1 direito ',
	'Calo Interdigital em Arteiro 2 direito ',
	'Calo Interdigital em Arteiro 3 direito ',
	'Calo Interdigital em Arteiro 4 direito ',
	'Calo Interdigital em pé esquerdo ',
	'Calo Interdigital em Halux esquerdo ',
	'Calo Interdigital em Arteiro 1 esquerdo ',
	'Calo Interdigital em Arteiro 2 esquerdo ',
	'Calo Interdigital em Arteiro 3 esquerdo ',
	'Calo Interdigital em Arteiro 4 esquerdo ',
	'Calo Plantar em pé direito ',
	'Calo Plantar em Halux direito ',
	'Calo Plantar em Arteiro 1 direito ',
	'Calo Plantar em Arteiro 2 direito ',
	'Calo Plantar em Arteiro 3 direito ',
	'Calo Plantar em Arteiro 4 direito ',
	'Calo Plantar em pé esquerdo ',
	'Calo Plantar em Halux esquerdo ',
	'Calo Plantar em Arteiro 1 esquerdo',
	'Calo Plantar em Arteiro 2 esquerdo',
	'Calo Plantar em Arteiro 3 esquerdo',
	'Calo Plantar em Arteiro 4 esquerdo',
	'Calo Dorsal em pé direito  ',
	'Calo Dorsal em Halux direito  ',
	'Calo Dorsal em Arteiro 1 direito',
	'Calo Dorsal em Arteiro 2 direito',
	'Calo Dorsal em Arteiro 3 direito',
	'Calo Dorsal em Arteiro 4 direito',
	'Calo Dorsal em pé esquerdo ',
	'Calo Dorsal em Halux esquerdo ',
	'Calo Dorsal em Arteiro 1 esquerdo ',
	'Calo Dorsal em Arteiro 2 esquerdo ',
	'Calo Dorsal em Arteiro 3 esquerdo ',
	'Calo Dorsal em Arteiro 4 esquerdo ',
	'Calo Miliar em pé direito ',
	'Calo Miliar em Halux direito ',
	'Calo Miliar em Arteiro 1 direito ',
	'Calo Miliar em Arteiro 2 direito ',
	'Calo Miliar em Arteiro 3 direito ',
	'Calo Miliar em Arteiro 4 direito ',
	'Calo Miliar em pé esquerdo',
	'Calo Miliar em Halux esquerdo',
	'Calo Miliar em Arteiro 1 esquerdo ',
	'Calo Miliar em Arteiro 2 esquerdo ',
	'Calo Miliar em Arteiro 3 esquerdo ',
	'Calo Miliar em Arteiro 4 esquerdo ',
	'Calo neurovascular em pé direito ',
	'Calo neurovascular em Halux direito ',
	'Calo neurovascular em Arteiro 1 direito',
	'Calo neurovascular em Arteiro 2 direito',
	'Calo neurovascular em Arteiro 3 direito',
	'Calo neurovascular em Arteiro 4 direito',
	'Calo neurovascular em pé esquerdo',
	'Calo neurovascular em Halux esquerdo',
	'Calo neurovascular em Arteiro 1 esquerdo ',
	'Calo neurovascular em Arteiro 2 esquerdo ',
	'Calo neurovascular em Arteiro 3 esquerdo ',
	'Calo neurovascular em Arteiro 4 esquerdo ',
];

export const NOMENCLATURA_DEDOS_PE = [
	'Pé direito ',
	'Halux direito ',
	'Arteiro 1 direito ',
	'Arteiro 2 direito ',
	'Arteiro 3 direito ',
	'Arteiro 4 direito ',
	'Pé esquerdo ',
	'Halux esquerdo ',
	'Arteiro 1 esquerdo ',
	'Arteiro 2 esquerdo ',
	'Arteiro 3 esquerdo ',
	'Arteiro 4 esquerdo ',
];

export const NOMENCLATURA_PES = ['Pé Direito', 'Pé Esquerdo'];
export const TIPOS_DE_PES = [
	'Pé Normal direito ',
	'Pé Normal esquerdo ',
	'Pé Cavo direito ',
	'Pé Cavo esquerdo ',
	'Pé Plano direito ',
	'Pé Plano esquerdo ',
];

export const TIPOS_PISADA_PES = [
	'Pé Pronado direito ',
	'Pé Pronado esquerdo ',
	'Pé Neutro direito ',
	'Pé Neutro esquerdo ',
	'Pé Supinado direito ',
	'Pé Supinado esquerdo ',
];

export const TIPOS_JOELHOS = ['Joelho Normal ', 'Joelho Valgo ', 'Joelho Varo '];

export const TIPOS_DEDOS = ['Dedo Egipcio', 'Dedo Romano ', 'Dedo Grego ', 'Dedo Alemão ', 'Dedo Celtico '];

export const FORMATO_UNHAS_JSON = [
	{ imgSrc: require('../../images/formato_unhas/normal.png'), fieldName: 'Unhas Normais', field: 'normal' },
	{ imgSrc: require('../../images/formato_unhas/involuta.png'), fieldName: 'Unhas Involutas', field: 'involuta' },
	{ imgSrc: require('../../images/formato_unhas/telha.png'), fieldName: 'Unhas em Telha', field: 'telha' },
	{ imgSrc: require('../../images/formato_unhas/funil.png'), fieldName: 'Unhas em Funil', field: 'funil' },
	{ imgSrc: require('../../images/formato_unhas/gancho.png'), fieldName: 'Unhas em Gancho', field: 'gancho' },
	{ imgSrc: require('../../images/formato_unhas/caracol.png'), fieldName: 'Unhas em Caracol', field: 'caracol' },
	{ imgSrc: require('../../images/formato_unhas/torques.png'), fieldName: 'Unhas em Torquês', field: 'torques' },
];

export const LESOES_UNHAS_JSON = [
	{
		imgSrc: require('../../images/lesoes_unhas/onicoatrofia2.jpg'),
		fieldName: 'Onicoatrofia',
		field: 'onicoatrofia',
	},
	{ imgSrc: require('../../images/lesoes_unhas/onicorrexe.png'), fieldName: 'Onicorrexe', field: 'onicorrexe' },
	{ imgSrc: require('../../images/lesoes_unhas/onicogrifose.jpg'), fieldName: 'Onicogrifose', field: 'onicogrifose' },
	{ imgSrc: require('../../images/lesoes_unhas/onicolise.jpg'), fieldName: 'Onicolise', field: 'onicolise' },
	{ imgSrc: require('../../images/lesoes_unhas/onicomicose.jpg'), fieldName: 'Onicomicose', field: 'onicomicose' },
	{ imgSrc: require('../../images/lesoes_unhas/psoriase.jpg'), fieldName: 'Psoriase', field: 'psoriase' },
	{ imgSrc: require('../../images/lesoes_unhas/onicomicose.jpg'), fieldName: 'Onicomicose', field: 'onicocriptose' },
	{ imgSrc: require('../../images/lesoes_unhas/granuloma.jpg'), fieldName: 'Granuloma', field: 'granuloma' },
	{ imgSrc: require('../../images/lesoes_unhas/alteracao_cor.jpeg'), fieldName: 'Alteração Cor', field: 'alter_cor' },
	{ imgSrc: require('../../images/lesoes_unhas/onicofose.jpg'), fieldName: 'Onicofose', field: 'onicofose' },
	{ imgSrc: require('../../images/lesoes_unhas/exostose.png'), fieldName: 'Exostose', field: 'exostose' },
	{ imgSrc: require('../../images/lesoes_unhas/onicomadese.png'), fieldName: 'Onicomadese', field: 'onicomadese' },
];

export const LESOES_PELE_JSON = [
	{
		imgSrc: require('../../images/lesoes_pele/bromidrose.jpg'),
		fieldName: 'Bromidrose',
		field: 'bromidrose',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{
		imgSrc: require('../../images/lesoes_pele/anidrose.jpg'),
		fieldName: 'Anidrose',
		field: 'anidrose',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{
		imgSrc: require('../../images/lesoes_pele/hiperhidrose.jpg'),
		fieldName: 'Hiperhidrose',
		field: 'hiperhidrose',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{
		imgSrc: require('../../images/lesoes_pele/isquemia.png'),
		fieldName: 'Isquemia',
		field: 'isquemia',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{
		imgSrc: require('../../images/lesoes_pele/tinea_pedis.jpg'),
		fieldName: 'Tinea Pedis',
		field: 'tinea_pedis',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{
		imgSrc: require('../../images/lesoes_pele/fissuras.jpg'),
		fieldName: 'Fissuras',
		field: 'fissuras',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{
		imgSrc: require('../../images/lesoes_pele/desidrose.jpg'),
		fieldName: 'Desidrose',
		field: 'desidrose',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{
		imgSrc: require('../../images/lesoes_pele/mal_perfurante.jpg'),
		fieldName: 'Mal Perfurante',
		field: 'mal_perfurante',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{
		imgSrc: require('../../images/lesoes_pele/psoriase.jpg'),
		fieldName: 'Psoriase',
		field: 'psoriase',
		options: NOMENCLATURA_DEDOS_PE,
	},
	{ imgSrc: require('../../images/lesoes_pele/calos.jpg'), fieldName: 'Calos', field: 'calos', options: CALOS_JSON },
];

export const LESOES_ORTO_JSON = [
	{
		imgSrc: require('../../images/lesoes_ortopedicas/halux_valgus.jpg'),
		fieldName: 'Halux Valgus',
		field: 'halux_valgus',
		options: [
			'Pé direito ',
			'Halux direito ',
			'Arteiro 1 direito ',
			'Arteiro 2 direito ',
			'Arteiro 3 direito ',
			'Arteiro 4 direito ',
			'Pé esquerdo ',
			'Halux esquerdo ',
			'Arteiro 1 esquerdo ',
			'Arteiro 2 esquerdo ',
			'Arteiro 3 esquerdo ',
			'Arteiro 4 esquerdo ',
		],
	},
	{
		imgSrc: require('../../images/lesoes_ortopedicas/halux_rigidus.jpg'),
		fieldName: 'Halux Rigidus',
		field: 'halux_rigidus',
		options: [
			'Pé direito ',
			'Halux direito ',
			'Arteiro 1 direito ',
			'Arteiro 2 direito ',
			'Arteiro 3 direito ',
			'Arteiro 4 direito ',
			'Pé esquerdo ',
			'Halux esquerdo ',
			'Arteiro 1 esquerdo ',
			'Arteiro 2 esquerdo ',
			'Arteiro 3 esquerdo ',
			'Arteiro 4 esquerdo ',
		],
	},
	{
		imgSrc: require('../../images/lesoes_ortopedicas/esporao_calcaneo.jpeg'),
		fieldName: 'Esporão Calcaneo',
		field: 'esporao_calcaneo',
		options: ['Pé Direito', 'Pé Esquerdo'],
	},
	{
		imgSrc: require('../../images/lesoes_ortopedicas/dedos_garra.png'),
		fieldName: 'Dedos Garra',
		field: 'dedos_garra',
		options: [
			'Pé direito ',
			'Halux direito ',
			'Arteiro 1 direito ',
			'Arteiro 2 direito ',
			'Arteiro 3 direito ',
			'Arteiro 4 direito ',
			'Pé esquerdo ',
			'Halux esquerdo ',
			'Arteiro 1 esquerdo ',
			'Arteiro 2 esquerdo ',
			'Arteiro 3 esquerdo ',
			'Arteiro 4 esquerdo ',
		],
	},
	{
		imgSrc: require('../../images/lesoes_ortopedicas/tipo_pe.jpg'),
		fieldName: 'Tipo pé',
		field: 'tipo_pe',
		options: [
			'Pé Normal direito ',
			'Pé Normal esquerdo ',
			'Pé Cavo direito ',
			'Pé Cavo esquerdo ',
			'Pé Plano direito ',
			'Pé Plano esquerdo ',
		],
	},
	{
		imgSrc: require('../../images/lesoes_ortopedicas/tipos_de_pisada.jpg'),
		fieldName: 'Tipos pisada',
		field: 'tipos_pisada',
		options: [
			'Pé Pronado direito ',
			'Pé Pronado esquerdo ',
			'Pé Neutro direito ',
			'Pé Neutro esquerdo ',
			'Pé Supinado direito ',
			'Pé Supinado esquerdo ',
		],
	},
	{
		imgSrc: require('../../images/lesoes_ortopedicas/tipos_joelhos.jpg'),
		fieldName: 'Tipos joehos',
		field: 'tipos_joelho',
		options: ['Joelho Normal ', 'Joelho Valgo ', 'Joelho Varo '],
	},
	{
		imgSrc: require('../../images/lesoes_ortopedicas/tipos_dedos_pe.jpg'),
		fieldName: 'Tipos dedos pé',
		field: 'tipos_dedos',
		options: ['Dedo Egipcio', 'Dedo Romano ', 'Dedo Grego ', 'Dedo Alemão ', 'Dedo Celtico '],
	},
];
